Repository Typeform/.github, pull requests merged in 2025-05, with the labels that each got.

#129 Improve shared action for updating GraphQL-BFF AllowList
  .github/workflows/graphql-generate-persisted-operations.yml
Labels: missing-jira, 5 min review

#130 adds config for generation of persisted query allow list
  .github/workflows/graphql-generate-persisted-operations.yml
Labels: 1 min review, missing-jira

#131 feat(NOJIRA-1): add merge queue event on ci-standard-checks
  .github/workflows/ci-standard-checks.yml
Labels: 1 min review
