Repository Typeform/.github, pull requests merged in 2025-09, with the labels that each got.

#143 feat(image-multiarch): allow to configure self-hosted runner
  .github/workflows/ci-standard-checks-workflow.yaml
  .github/workflows/comment-deploy-link.yaml
  .github/workflows/deep-purple-checks.yml
  .github/workflows/go-lint-workflow.yaml
  .github/workflows/graphql-generate-persisted-operations.yml
  .github/workflows/image-multiarch.yaml
Labels: 5 min review

#145 feat: dynamic golangci-lint versions and configuration
  .github/workflows/go-lint-workflow.yaml
Labels: 1 min review

#152 chore(go-lint): [NOJIRA-1234] comment fix command
  .github/workflows/go-lint-workflow.yaml
Labels: 1 min review, missing-jira
